.TH "core/system/BulkLoader.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/system/BulkLoader.h
.SH SYNOPSIS
.br
.PP
\fC#include 'json\&.hpp'\fP
.br
\fC#include <map>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QVector2D>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBulkLoader\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = \fBnlohmann::json\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBjson\fP =  \fBnlohmann::json\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
