.TH "bin/Debug/CMakeCache.txt" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/Debug/CMakeCache.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "CMAKE_BUILD_TYPE \fB__pad0__\fP"
.br
.ti -1c
.RI "\fBqtmain\fP"
.br
.ti -1c
.RI "\fBgeneral\fP"
.br
.ti -1c
.RI "\fBforge_gui\fP"
.br
.ti -1c
.RI "forge_gui_LIB_DEPENDS \fB__pad1__\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "CMAKE_BUILD_TYPE __pad0__"

.SS "forge_gui_LIB_DEPENDS __pad1__"

.SS "forge_gui"

.SS "general"

.SS "qtmain"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
