.TH "Derived_from< T, B >" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Derived_from< T, B >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IdentifierList\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDerived_from\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBconstraints\fP (T *p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , class B > \fBDerived_from\fP< T, B >::\fBDerived_from\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T , class B > static void \fBDerived_from\fP< T, B >::constraints (T * p)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
