.TH "core/dependencies/earcut.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/dependencies/earcut.h
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmapbox::util::nth< I, T >\fP"
.br
.ti -1c
.RI "class \fBmapbox::detail::Earcut< N >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmapbox\fP"
.br
.ti -1c
.RI " \fBmapbox::util\fP"
.br
.ti -1c
.RI " \fBmapbox::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename N  = uint32_t, typename Polygon > std::vector< N > \fBmapbox::earcut\fP (const Polygon &poly)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
