.TH "gui/components/EventFilters.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/components/EventFilters.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include 'Messages\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCloseEventFilter\fP"
.br
.RI "Event filter for close events\&. "
.ti -1c
.RI "class \fBClickEventFilter\fP"
.br
.RI "Event filter for click events\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
