.TH "FCameraController" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FCameraController
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FCameraController\&.h>\fP
.PP
Inherits QtAbstractController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFCameraController\fP ()"
.br
.RI "The constructor\&. "
.ti -1c
.RI "void \fBmoveCamera\fP (const InputState &state, float dt) override"
.br
.RI "The overriden camera control function\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FCameraController::FCameraController ()"

.PP
The constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void FCameraController::moveCamera (const InputState & state, float dt)\fC [override]\fP"

.PP
The overriden camera control function\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
