.TH "core/symbols/FCrossSection.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/symbols/FCrossSection.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui/QVector2D>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br
\fC#include 'FGeometry\&.h'\fP
.br
\fC#include 'FSymbol\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFCrossSection\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEPTH_NORMAL\fP   QVector3D(0\&.0, 0\&.0, 1\&.0)"
.br
.ti -1c
.RI "#define \fBDEPTH_LENGTH\fP   0\&.5"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEPTH_LENGTH   0\&.5"

.SS "#define DEPTH_NORMAL   QVector3D(0\&.0, 0\&.0, 1\&.0)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
