.TH "core/models/FModel.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/models/FModel.h
.SH SYNOPSIS
.br
.PP
\fC#include <Qt3DCore/QEntity>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br
\fC#include <Qt3DRender/QGeometryRenderer>\fP
.br
\fC#include <HasIdentifier\&.h>\fP
.br
\fC#include 'ForgeWindow\&.h'\fP
.br
\fC#include 'FMaterial\&.h'\fP
.br
\fC#include 'FGeometry\&.h'\fP
.br
\fC#include 'FSymbol\&.h'\fP
.br
\fC#include 'Defines\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFModel\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRED\fP   QColor::fromRgbF(1\&.0,0\&.3,0\&.3)"
.br
.ti -1c
.RI "#define \fBPI\fP   3\&.14159265358979323846"
.br
.ti -1c
.RI "#define \fBax\fP(r,  a)   (r * std::cosf(a))"
.br
.ti -1c
.RI "#define \fBay\fP(r,  a)   (r * std::sinf(a))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ax(r, a)   (r * std::cosf(a))"

.SS "#define ay(r, a)   (r * std::sinf(a))"

.SS "#define PI   3\&.14159265358979323846"

.SS "#define RED   QColor::fromRgbF(1\&.0,0\&.3,0\&.3)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
