.TH "gui/controls/ForgeCreate.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/controls/ForgeCreate.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ForgeControl\&.h'\fP
.br
\fC#include 'BulkLoader\&.h'\fP
.br
\fC#include 'FModel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForgeCreate\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPlacementType\fP { \fBPlacementType::None\fP, \fBPlacementType::Start\fP, \fBPlacementType::End\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPlacementType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIStart \fP\fP
.TP
\fB\fIEnd \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
