.TH "gui/controls/ForgeControl.cpp" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/controls/ForgeControl.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ForgeControl\&.h'\fP
.br
\fC#include 'ForgeWindow\&.h'\fP
.br
\fC#include 'ForgeApplication\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
