.TH "gui/controls/ForgeMainMenu.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/controls/ForgeMainMenu.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets/QMenuBar>\fP
.br
\fC#include 'ForgeControl\&.h'\fP
.br
\fC#include 'ForgeWindow\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForgeMainMenu\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRootMenu\fP { \fBRootMenu::File\fP, \fBRootMenu::View\fP, \fBRootMenu::Settings\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRootMenu\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFile \fP\fP
.TP
\fB\fIView \fP\fP
.TP
\fB\fISettings \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
