.TH "ForgeTitleBar" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ForgeTitleBar
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ForgeTitleBar\&.h>\fP
.PP
Inherits \fBFWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForgeTitleBar\fP (QWidget *t_parent)"
.br
.RI "Construct the title bar\&. "
.ti -1c
.RI "void \fBcloseControl\fP ()"
.br
.RI "Close the parent (the control) when the X button is clicked\&. "
.ti -1c
.RI "void \fBsetTitle\fP (QString t_title)"
.br
.RI "Set the title bar text\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ForgeTitleBar::ForgeTitleBar (QWidget * t_parent)"

.PP
Construct the title bar\&. 
.SH "Member Function Documentation"
.PP 
.SS "void ForgeTitleBar::closeControl ()"

.PP
Close the parent (the control) when the X button is clicked\&. 
.SS "void ForgeTitleBar::setTitle (QString t_title)"

.PP
Set the title bar text\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
