.TH "ForgeTitleButton" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ForgeTitleButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ForgeTitleBar\&.h>\fP
.PP
Inherits QPushButton\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForgeTitleButton\fP (QString t_icon)"
.br
.RI "Create button with an icon\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ForgeTitleButton::ForgeTitleButton (QString t_icon)"

.PP
Create button with an icon\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
