.TH "gui/controls/ForgeControl.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/controls/ForgeControl.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets/QDialog>\fP
.br
\fC#include 'HasIdentifier\&.h'\fP
.br
\fC#include 'ForgeTitleBar\&.h'\fP
.br
\fC#include 'Messages\&.h'\fP
.br
\fC#include 'Message\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForgeControl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
