.TH "gui/windows/ForgeWindow.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/windows/ForgeWindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QDir>\fP
.br
\fC#include <QOpenGLFunctions>\fP
.br
\fC#include 'IdentifierList\&.h'\fP
.br
\fC#include 'HasIdentifier\&.h'\fP
.br
\fC#include 'Messages\&.h'\fP
.br
\fC#include 'Defines\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForgeWindow\fP"
.br
.RI "The main 3D window class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
