.TH "gui/windows/ForgeWindow.cpp" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/windows/ForgeWindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QDesktopWidget>\fP
.br
\fC#include <QtWidgets/QDockWidget>\fP
.br
\fC#include <Qt3DExtras/QCuboidMesh>\fP
.br
\fC#include <Qt3DExtras/QOrbitCameraController>\fP
.br
\fC#include <Qt3DRender/QCamera>\fP
.br
\fC#include <Qt3DRender/QMaterial>\fP
.br
\fC#include <Qt3DRender/QMesh>\fP
.br
\fC#include <Qt3DExtras/QGoochMaterial>\fP
.br
\fC#include <Qt3DExtras/QPerVertexColorMaterial>\fP
.br
\fC#include <Qt3DExtras/QTorusMesh>\fP
.br
\fC#include <Qt3DCore/QTransform>\fP
.br
\fC#include <Qt3DRender/QLineWidth>\fP
.br
\fC#include <Qt3DRender/QViewport>\fP
.br
\fC#include <Qt3DRender/QScreenRayCaster>\fP
.br
\fC#include 'ForgeApplication\&.h'\fP
.br
\fC#include 'ForgeWindow\&.h'\fP
.br
\fC#include 'ForgeControl\&.h'\fP
.br
\fC#include 'exceptions\&.h'\fP
.br
\fC#include 'Defines\&.h'\fP
.br
\fC#include 'EventFilters\&.h'\fP
.br
\fC#include 'Config\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBLACK\fP   0x000000"
.br
.ti -1c
.RI "#define \fBGRAY\fP   0x212121"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLACK   0x000000"

.SS "#define GRAY   0x212121"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
