.TH "gui/windows/ForgeApplication.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/windows/ForgeApplication.h
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <Qt3DExtras/QAbstractCameraController>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <Qt3DInput/QInputSettings>\fP
.br
\fC#include <Qt3DRender/QFrameGraphNode>\fP
.br
\fC#include <Qt3DRender/QRenderSettings>\fP
.br
\fC#include <Qt3DCore/QAspectEngine>\fP
.br
\fC#include <Qt3DRender/QRenderAspect>\fP
.br
\fC#include <Qt3DInput/QInputAspect>\fP
.br
\fC#include <Qt3DLogic/QLogicAspect>\fP
.br
\fC#include <QPickingSettings>\fP
.br
\fC#include <Qt3DRender/QRenderStateSet>\fP
.br
\fC#include <Qt3DRender/QLineWidth>\fP
.br
\fC#include 'IdentifierList\&.h'\fP
.br
\fC#include 'ForgeWindow\&.h'\fP
.br
\fC#include 'ForgeControl\&.h'\fP
.br
\fC#include 'FCameraController\&.h'\fP
.br
\fC#include 'FModel\&.h'\fP
.br
\fC#include 'Defines\&.h'\fP
.br
\fC#include 'Messages\&.h'\fP
.br
\fC#include 'Message\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForgeApplication\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
