.TH "gui/controls/FOrigin.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/controls/FOrigin.h
.SH SYNOPSIS
.br
.PP
\fC#include 'FModel\&.h'\fP
.br
\fC#include 'FLine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFOrigin\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
