.TH "FOrigin" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FOrigin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FOrigin\&.h>\fP
.PP
Inherits \fBFModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFOrigin\fP ()"
.br
.RI "Construct the three \fBFModel\fP objects that make up the origin display (x, y and z axis lines)\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FOrigin::FOrigin ()"

.PP
Construct the three \fBFModel\fP objects that make up the origin display (x, y and z axis lines)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
