.TH "core/symbols/FSymbol.cpp" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/symbols/FSymbol.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FSymbol\&.h'\fP
.br
\fC#include 'FCrossSection\&.h'\fP
.br
\fC#include 'FLine\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_match\fP(f,  t,  N,  T,  V)   \fBif\fP(T == json::value_t::f) return setProperty(N,(t)V)			\\"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _match(f, t, N, T, V)   \fBif\fP(T == json::value_t::f) return setProperty(N,(t)V)			\\"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
