.TH "FWidget" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FWidget\&.h>\fP
.PP
Inherits QWidget\&.
.PP
Inherited by \fBForgeTitleBar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFWidget\fP ()"
.br
.ti -1c
.RI "\fBFWidget\fP (QWidget *t_parent)"
.br
.ti -1c
.RI "void \fBsetDragTarget\fP (QWidget *t_target)"
.br
.ti -1c
.RI "void \fBsetDrag\fP (bool t_drag)"
.br
.ti -1c
.RI "bool \fBisDragging\fP ()"
.br
.ti -1c
.RI "void \fBsetPosition\fP (int x, int y)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FWidget::FWidget ()\fC [inline]\fP"

.SS "FWidget::FWidget (QWidget * t_parent)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool FWidget::isDragging ()\fC [inline]\fP"

.SS "void FWidget::setDrag (bool t_drag)\fC [inline]\fP"

.SS "void FWidget::setDragTarget (QWidget * t_target)\fC [inline]\fP"

.SS "void FWidget::setPosition (int x, int y)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
