.TH "gui/components/IdentifierList.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/components/IdentifierList.h
.SH SYNOPSIS
.br
.PP
\fC#include 'HasIdentifier\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDerived_from< T, B >\fP"
.br
.ti -1c
.RI "class \fBIdentifierList< T >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBgt_zero\fP(s)   \fBif\fP(s <= 0) return nullptr"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define gt_zero(s)   \fBif\fP(s <= 0) return nullptr"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
