.TH "io" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdetail\fP"
.br
.ti -1c
.RI " \fBerror\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBByteSourceBase\fP"
.br
.ti -1c
.RI "class \fBCSVReader\fP"
.br
.ti -1c
.RI "struct \fBdouble_quote_escape\fP"
.br
.ti -1c
.RI "struct \fBempty_line_comment\fP"
.br
.ti -1c
.RI "struct \fBignore_overflow\fP"
.br
.ti -1c
.RI "class \fBLineReader\fP"
.br
.ti -1c
.RI "struct \fBno_comment\fP"
.br
.ti -1c
.RI "struct \fBno_quote_escape\fP"
.br
.ti -1c
.RI "struct \fBset_to_max_on_overflow\fP"
.br
.ti -1c
.RI "struct \fBsingle_and_empty_line_comment\fP"
.br
.ti -1c
.RI "struct \fBsingle_line_comment\fP"
.br
.ti -1c
.RI "struct \fBthrow_on_overflow\fP"
.br
.ti -1c
.RI "struct \fBtrim_chars\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBignore_column\fP = unsigned int"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBio::ignore_column\fP = typedef unsigned int"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
