.TH "io::detail::NonOwningIStreamByteSource" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::detail::NonOwningIStreamByteSource
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csv\&.h>\fP
.PP
Inherits \fBio::ByteSourceBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonOwningIStreamByteSource\fP (std::istream &in)"
.br
.ti -1c
.RI "int \fBread\fP (char *buffer, int size)"
.br
.ti -1c
.RI "\fB~NonOwningIStreamByteSource\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "io::detail::NonOwningIStreamByteSource::NonOwningIStreamByteSource (std::istream & in)\fC [inline]\fP, \fC [explicit]\fP"

.SS "io::detail::NonOwningIStreamByteSource::~NonOwningIStreamByteSource ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int io::detail::NonOwningIStreamByteSource::read (char * buffer, int size)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBio::ByteSourceBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
