.TH "io::error" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::error
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbase\fP"
.br
.ti -1c
.RI "struct \fBcan_not_open_file\fP"
.br
.ti -1c
.RI "struct \fBduplicated_column_in_header\fP"
.br
.ti -1c
.RI "struct \fBescaped_string_not_closed\fP"
.br
.ti -1c
.RI "struct \fBextra_column_in_header\fP"
.br
.ti -1c
.RI "struct \fBheader_missing\fP"
.br
.ti -1c
.RI "struct \fBinteger_must_be_positive\fP"
.br
.ti -1c
.RI "struct \fBinteger_overflow\fP"
.br
.ti -1c
.RI "struct \fBinteger_underflow\fP"
.br
.ti -1c
.RI "struct \fBinvalid_single_character\fP"
.br
.ti -1c
.RI "struct \fBline_length_limit_exceeded\fP"
.br
.ti -1c
.RI "struct \fBmissing_column_in_header\fP"
.br
.ti -1c
.RI "struct \fBno_digit\fP"
.br
.ti -1c
.RI "struct \fBtoo_few_columns\fP"
.br
.ti -1c
.RI "struct \fBtoo_many_columns\fP"
.br
.ti -1c
.RI "struct \fBwith_column_content\fP"
.br
.ti -1c
.RI "struct \fBwith_column_name\fP"
.br
.ti -1c
.RI "struct \fBwith_errno\fP"
.br
.ti -1c
.RI "struct \fBwith_file_line\fP"
.br
.ti -1c
.RI "struct \fBwith_file_name\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBmax_file_name_length\fP = 255"
.br
.ti -1c
.RI "const int \fBmax_column_name_length\fP = 63"
.br
.ti -1c
.RI "const int \fBmax_column_content_length\fP = 63"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int io::error::max_column_content_length = 63"

.SS "const int io::error::max_column_name_length = 63"

.SS "const int io::error::max_file_name_length = 255"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
