.TH "io::empty_line_comment" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::empty_line_comment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csv\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBis_comment\fP (const char *line)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool io::empty_line_comment::is_comment (const char * line)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
