.TH "io::error::integer_must_be_positive" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::error::integer_must_be_positive
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csv\&.h>\fP
.PP
Inherits \fBio::error::base\fP, \fBio::error::with_file_name\fP, \fBio::error::with_file_line\fP, \fBio::error::with_column_name\fP, and \fBio::error::with_column_content\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBformat_error_message\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void io::error::integer_must_be_positive::format_error_message () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBio::error::base\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
