.TH "io::set_to_max_on_overflow" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::set_to_max_on_overflow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csv\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T > static void \fBon_overflow\fP (T &x)"
.br
.ti -1c
.RI "template<class T > static void \fBon_underflow\fP (T &x)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class T > static void io::set_to_max_on_overflow::on_overflow (T & x)\fC [inline]\fP, \fC [static]\fP"

.SS "template<class T > static void io::set_to_max_on_overflow::on_underflow (T & x)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
