.TH "io::trim_chars< trim_char_list >" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io::trim_chars< trim_char_list >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csv\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtrim\fP (char *&str_begin, char *&str_end)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<char \&.\&.\&. trim_char_list> static void \fBio::trim_chars\fP< trim_char_list >::trim (char *& str_begin, char *& str_end)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
