.TH "core/system/Logger.cpp" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/system/Logger.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Logger\&.h'\fP
.br
\fC#include 'Resources\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlogging\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTAMP_FORMAT\fP   '%Y%m%d'"
.br
.ti -1c
.RI "#define \fBDATE_FORMAT\fP   '%Y\-%m\-%d %H:%M:%S'"
.br
.ti -1c
.RI "#define \fBLEVEL_STR\fP(l)   _log_map[(int)l]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATE_FORMAT   '%Y\-%m\-%d %H:%M:%S'"

.SS "#define LEVEL_STR(l)   _log_map[(int)l]"

.SS "#define STAMP_FORMAT   '%Y%m%d'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
