.TH "logging" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogger\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLogLevel\fP { \fBLogLevel::Debug\fP = 0, \fBLogLevel::Info\fP = 1, \fBLogLevel::Warning\fP = 2, \fBLogLevel::Error\fP = 3 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlogging::LogLevel\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDebug \fP\fP
.TP
\fB\fIInfo \fP\fP
.TP
\fB\fIWarning \fP\fP
.TP
\fB\fIError \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
