.TH "logging::Logger" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging::Logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Logger\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Logger\fP ()"
.br
.ti -1c
.RI "void \fBlog\fP (const char *t_file, const int t_line, const \fBLogLevel\fP t_level, const char *t_message)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLogger\fP * \fBinstance\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "logging::Logger::~Logger ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBLogger\fP * logging::Logger::instance ()\fC [static]\fP"

.SS "void logging::Logger::log (const char * t_file, const int t_line, const \fBLogLevel\fP t_level, const char * t_message)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
