.TH "bin/Debug/CMakeFiles/ShowIncludes/main.c" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/Debug/CMakeFiles/ShowIncludes/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'foo\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
