.TH "mapbox::util::nth< I, T >" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mapbox::util::nth< I, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <earcut\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::tuple_element< I, T >::type \fBget\fP (const T &t)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<std::size_t I, typename T > static std::tuple_element<I, T>::type \fBmapbox::util::nth\fP< I, T >::get (const T & t)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
