.TH "mapbox::detail::Earcut< N >" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mapbox::detail::Earcut< N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <earcut\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Polygon > void \fBoperator()\fP (const Polygon &points)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< N > \fBindices\fP"
.br
.ti -1c
.RI "std::size_t \fBvertices\fP = 0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename N > template<typename Polygon > void \fBmapbox::detail::Earcut\fP< N >::operator() (const Polygon & points)"

.SH "Member Data Documentation"
.PP 
.SS "template<typename N  = uint32_t> std::vector<N> \fBmapbox::detail::Earcut\fP< N >::indices"

.SS "template<typename N  = uint32_t> std::size_t \fBmapbox::detail::Earcut\fP< N >::vertices = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
