.TH "mapbox" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mapbox
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdetail\fP"
.br
.ti -1c
.RI " \fButil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename N  = uint32_t, typename Polygon > std::vector< N > \fBearcut\fP (const Polygon &poly)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename N  = uint32_t, typename Polygon > std::vector<N> mapbox::earcut (const Polygon & poly)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
