.TH "Message< T >" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP (\fBHandler\fP *t_sender, T t_value)"
.br
.ti -1c
.RI "T \fBvalue\fP ()"
.br
.ti -1c
.RI "const char * \fBname\fP ()"
.br
.ti -1c
.RI "\fBHandler\fP * \fBsender\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBMessage\fP< T >::\fBMessage\fP (\fBHandler\fP * t_sender, T t_value)"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const char* \fBMessage\fP< T >::name ()"

.SS "template<typename T > \fBHandler\fP* \fBMessage\fP< T >::sender ()"

.SS "template<typename T > T \fBMessage\fP< T >::value ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
