.TH "nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits \fBnlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
