.TH "nlohmann::detail::from_json_fn" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::from_json_fn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType , typename T > auto \fBoperator()\fP (const BasicJsonType &j, T &val) const noexcept(noexcept(\fBfrom_json\fP(j, val))) \-> decltype(\fBfrom_json\fP(j, val), \fBvoid\fP())"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename T > auto nlohmann::detail::from_json_fn::operator() (const BasicJsonType & j, T & val) const \-> decltype(\fBfrom_json\fP(j, val), \fBvoid\fP())
    \fC [inline]\fP, \fC [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
