.TH "nlohmann::detail::detector< Default, void_t< Op< Args... > >, Op, Args... >" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::detector< Default, void_t< Op< Args... > >, Op, Args... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_t\fP = std::true_type"
.br
.ti -1c
.RI "using \fBtype\fP = Op< Args\&.\&.\&. >"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::\fBtype\fP =  Op<Args\&.\&.\&.>"

.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::\fBvalue_t\fP =  std::true_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
