.TH "qt_meta_stringdata_ForgeMainMenu_t" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_ForgeMainMenu_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [5]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [49]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QByteArrayData qt_meta_stringdata_ForgeMainMenu_t::data[5]"

.SS "char qt_meta_stringdata_ForgeMainMenu_t::stringdata0[49]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
