.TH "core/system/Resources.h" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/system/Resources.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QDir>\fP
.br
\fC#include <QtGui/QPixmap>\fP
.br
\fC#include <QtGui/QIcon>\fP
.br
\fC#include <map>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <filesystem>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBresources\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_INVALID_PATH\fP   \-1"
.br
.ti -1c
.RI "#define \fBF_NO_ACCESS\fP   \-2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBresources::initialize\fP (std::string t_root)"
.br
.ti -1c
.RI "void \fBresources::initialize\fP (QString t_root)"
.br
.ti -1c
.RI "QByteArray \fBresources::shader\fP (QString t_file)"
.br
.ti -1c
.RI "QString \fBresources::theme\fP (QString t_file)"
.br
.ti -1c
.RI "QIcon \fBresources::icon\fP (QString t_file)"
.br
.ti -1c
.RI "std::string \fBresources::data\fP (std::string t_name)"
.br
.ti -1c
.RI "std::string \fBresources::log\fP (std::string t_name)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F_INVALID_PATH   \-1"

.SS "#define F_NO_ACCESS   \-2"

.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
