.TH "UnknownMessage" 3 "Sat Apr 4 2020" "Version 0.1.0" "Forge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnknownMessage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnknownMessage\fP (\fBMessageType\fP t_type)"
.br
.ti -1c
.RI "virtual \fB~UnknownMessage\fP ()=default"
.br
.ti -1c
.RI "template<typename T > \fBMessage\fP< T > * \fBto\fP ()"
.br
.ti -1c
.RI "\fBMessageType\fP \fBtype\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnknownMessage::UnknownMessage (\fBMessageType\fP t_type)\fC [inline]\fP"

.SS "virtual UnknownMessage::~UnknownMessage ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBMessage\fP<T>* UnknownMessage::to ()\fC [inline]\fP"

.SS "\fBMessageType\fP UnknownMessage::type () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Forge from the source code\&.
