name: forge-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # install Qt5
      - name: Install Qt5
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.1'
          dir: 'C:/'
      
      # build Forge
      - name: Build Forge
        run: "&'build/windows.ps1'"

      # create an artifact package
      - name: Package Artifacts
        run: mkdir forge-release
        run: Copy-Item -Path "forge/Release/*" -Destination "forge-release" - Recurse
      
      # generate artifact zip and upload
      - name: Generate Artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: forge-release-${{github.run_id}}
          path: forge-release
