name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt5
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.1'
          dir: 'C:/'
      - name: Build Forge
        run: "&'build/windows.ps1'"
      - uses: actions/upload-artifact@v1
        if: success()
        with:
          name: forge-release-test
          path: .
